services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: calculator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calculator_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/calculator_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000,http://localhost
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_SMTP_STARTTLS: "false"
      APP_PUBLIC_BASE_URL: http://127.0.0.1:3000
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - back
    ports:
      - "3000:80"

volumes:
  postgres_data:
